### ISSUE TITLE
Holy Pandas no longer factory lubed

### ISSUE THREAD

**Issue by cringeybabey** [BWLR/switches.mx#11]
According to Drop's website, the Holy Pandas are no longer factory lubed, as of what I think was a while ago. "Unlubed from the factory" at the bottom of the "specs" list.

https://drop.com/buy/drop-invyr-holy-panda-mechanical-switches?defaultSelectionIds=965762

**Comment by BWLR** [comment]
Thanks for the heads up! I've now updated the website to reflect.
