### ISSUE TITLE
Add switches: Durock Shrimp

### ISSUE THREAD

**Issue by henrebotha** [BWLR/switches.mx#20]
https://divinikey.com/products/durock-shrimp-silent-tactile-switches

**Comment by craftyshark** [comment]
https://keeb.io/products/durock-shrimp-silent-tactile-t1-switches

Found a few specs, going to keep digging.

**Comment by BWLR** [comment]
Added to new switch page https://switches.mx/durock-t1-silent-shrimp

Thanks!
