### ISSUE TITLE
Everglide Aqua King acutation vs. bottom-out force

### ISSUE THREAD

**Issue by felker** [BWLR/switches.mx#29]
Entry currently reads 37/55/62/67g actuation force for the 4x variants: https://switches.mx/everglide-aqua-king?search=aqua%20king&

While consistent with Everglide's text on https://everglide.co/products/everglide-aqua-king-water-king-switches-v3?variant=42887000326356 , I believe it is incorrectly labeled. The force-graphs show that those forces are bottom-out forces, e.g. for 55g: https://everglide.co/cdn/shop/products/WK-7.webp?v=1654508796

This is discussed quite a bit on Reddit, Drop, Amazon listings.
See  https://github.com/bluepylons/Open-Switch-Curve-Meter/blob/main/Force%20curve%20measurements/Everglide-Aqua-King-55g.png for an independent check which confirms an actuation point around 40-45gf.

**Comment by BWLR** [comment]
I've now added some extra information to the [switch page](https://switches.mx/everglide-aqua-king?search=aqua%20king&)
![image](https://github.com/BWLR/switches.mx/assets/410142/b93176fd-e1b6-4fbd-a7f9-6f66c50dd5eb)
