### ISSUE TITLE
Add Stem length information

### ISSUE THREAD

**Issue by nicolkill** [BWLR/switches.mx#5]
Is very usefull know the length to compare with another to replace

**Comment by BWLR** [comment]
Recently done eg. https://switches.mx/gateron-cap-yellow

![image](https://user-images.githubusercontent.com/410142/133074586-ff7198cb-c6ad-42ce-90d9-d976d371fc3c.png)

**Comment by nicolkill** [comment]
@BWLR i think that the exact length would be great, ill check the code to add by my self
