### ISSUE TITLE
Add Lavendar Switch

### ISSUE THREAD

**Issue by SupaBeans** [BWLR/switches.mx#7]
No issue with the site. Wanted to give information to add Lavendar Switch

Make: Durock
Switch: Lavender 
Type: Linear
Act Force: 65g (est. bottom out)
Housing: Nylon (top & bottom)
Stem: POM
PCB mount
5 Pin
Factory lubed

more info here: https://cannonkeys.com/products/lavender-linear-switch

**Comment by BWLR** [comment]
I'll get this switch added next :)

**Comment by BWLR** [comment]
Here you go @SupaBeans https://switches.mx/lavender
